import { TabWidget } from "std-widgets.slint";
import { Utilities } from "Utilities.slint";
import { DumpInfoPage, SongInfoAdapter } from "DumpInfoPage.slint";
import { AddMapPage, CustomMapAdapter, CustomMapModel, MapInfo, MapInfoText } from "AddMapPage.slint";

export { Utilities, SongInfoAdapter, CustomMapAdapter, CustomMapModel, MapInfo, MapInfoText }

export component MainWindow inherits Window {
    width: 1200px;
    height: 800px;

    callback prompt_get_path() -> string;

    TabWidget {
        Tab {
            title: @tr("Mod generation");
            AddMapPage {
                prompt_get_path() => {
                    return root.prompt_get_path();
                }
            }
        }

        Tab {
            title: @tr("Dump song information");
            DumpInfoPage {
                prompt_get_path => {
                    self.path = root.prompt_get_path();
                    SongInfoAdapter.path = self.path;
                    SongInfoAdapter.load_data(0);
                    return self.path;
                }
            }
        }
    }
}
