[[patches]]
# TitleMenu::SetSound
offset = 0x017D9848
instruction = "MOV             W0, #0x125"

[[patches]]
# GallerySoundList::GetPlayingMusicID
offset = 0x017FF2B4
instruction = "MOV             W0, #0x125"

[[patches]]
# GameManager::Initialize
offset = 0x01802EF8
instruction = "CMP             W8, #0x125"

[[patches]]
# AppData::CreateMusicIDList
offset = 0x01894550
instruction = "MOV             W1, #0x125"

[[patches]]
# AppData::InitReleaseItems
offset = 0x0189628C
instruction = "MOV             W9, #0x125"

[[patches]]
# AppData::.cctor
offset = 0x0189CF14
instruction = "MOV             W10, #0x125"

[[patches]]
# SceneCharacterSelect::SetGameSetting
offset = 0x01AEC22C
instruction = "CMP             W10, #0x125"

[[patches]]
# SceneCharacterSelect::SetMusicTitle
offset = 0x01AEC528
instruction = "CMP             W21, #0x125"

[[patches]]
# StageSelectPanel::SetDetail
offset = 0x01B6225C
instruction = "CMP             W22, #0x125"

[[patches]]
# StageSoundList::Init
offset = 0x01B62968
instruction = "CMP             W28, #0x125"

[[patches]]
# StageSoundList::SetStageSoundList
offset = 0x01B62BE4
instruction = "CMP             W8, #0x125"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01B632EC
instruction = "CMP             W19, #0x125"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B63614
instruction = "CMP             W9, #0x125"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B63734
instruction = "CMP             W9, #0x125"

[[patches]]
# StageSoundList::UpdateSort
offset = 0x01B64740
instruction = "MOV             W1, #0x125"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B64F38
instruction = "CMP             W23, #0x125"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B64FA8
instruction = "CMP             W23, #0x125"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B654A4
instruction = "CMP             W22, #0x125"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B65514
instruction = "CMP             W22, #0x125"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA5D8
instruction = "CMP             W26, #0x125"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA67C
instruction = "CMP             W24, #0x125"

[[patches]]
# MusicData::.cctor
offset = 0x01BCAF98
instruction = "MOV             W19, #0x125"

[[patches]]
# MusicData.<InitializeAsync>d__4::MoveNext
offset = 0x01C154E8
instruction = "MOV             W20, #0x125"

[[patches]]
# MusicData.<InitializeAsync>d__4::MoveNext
offset = 0x01C156D4
instruction = "MOV             W20, #0x125"

[[patches]]
# MusicData.<InitializeAsync>d__4::MoveNext
offset = 0x01C162F8
instruction = "MOV             W20, #0x125"

[[patches]]
# ChallengeData.<InitializeAsync>d__4::MoveNext
offset = 0x01C5439C
instruction = "MOV             W8, #0x125"

[[patches]]
# RuleSetting::Init
offset = 0x01F09ABC
instruction = "MOV             W8, #0x125"

[[patches]]
# SceneGallery::get_IsPlaying
offset = 0x01FCEE14
instruction = "CMP             W8, #0x125"

[[patches]]
# SceneGallery::Update
offset = 0x01FCF6FC
instruction = "CMP             W8, #0x125"

[[patches]]
# SceneGallery::CheckBGM
offset = 0x01FCFDB4
instruction = "CMP             W8, #0x125"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FD00CC
instruction = "CMP             W8, #0x125"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FD00E4
instruction = "CMP             W8, #0x125"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FD08E8
instruction = "MOV             W8, #0x125"

[[patches]]
# SceneGallery::.ctor
offset = 0x01FD1D00
instruction = "MOV             W8, #0x125"

[[patches]]
# SceneMainMenu::InitGameSetting
offset = 0x01FDD1C0
instruction = "MOV             W0, #0x125"

[[patches]]
# InformationData.<InitializeAsync>d__4::MoveNext
offset = 0x020E2368
instruction = "MOV             W21, #0x125"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B6359C
instruction = "CMP             W22, #0x124"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B636B4
instruction = "CMP             W22, #0x124"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B637C4
instruction = "CMP             W20, #0x124"

[[patches]]
# StageSelectPanel::PushButtonUD
offset = 0x01B64B7C
instruction = "MOV             W1, #0x124"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B65350
instruction = "MOV             W1, #0x124"

[[patches]]
# StageSelectPanel::PushButtonX
offset = 0x01B65AAC
instruction = "MOV             W1, #0x124"

[[patches]]
# MusicData::GetInfo
offset = 0x01BC9F00
instruction = "CMP             W20, #0x124"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA384
instruction = "MOV             W1, #0x124"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA3D8
instruction = "CMP             W20, #0x124"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA418
instruction = "CMP             W21, #0x124"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA4C4
instruction = "CMP             W20, #0x124"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCAA98
instruction = "CMP             W9, #0x124"

[[patches]]
# MusicData.<InitializeAsync>d__4::MoveNext
offset = 0x01C15364
instruction = "MOV             W1, #0x124"

[[patches]]
# GameSoundManager.<LoadAllMusicAsync>d__9::MoveNext
offset = 0x01C242E0
instruction = "CMP             W20, #0x124"

[[patches]]
# AppData::SortMusic
offset = 0x0189C428
instruction = "CMP             W8, #0x123"

[[patches]]
# AppData::SortMusic
offset = 0x0189C49C
instruction = "CMP             W8, #0x123"

[[patches]]
# SceneCharacterSelect::Update
offset = 0x01AE2250
instruction = "MOV             W22, #0x11F"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01B63308
instruction = "MOV             W0, #0x11F"

[[patches]]
# SceneChallenge.<Start>d__25::MoveNext
offset = 0x01DAB7EC
instruction = "MOV             W0, #0x11F"

[[patches]]
# SceneCharacterSelect.<CloseStageSelectPanel>d__115::MoveNext
offset = 0x01DAC270
instruction = "MOV             W0, #0x11F"

[[patches]]
# SceneCharacterSelect.<HandleErrorAsync>d__147::MoveNext
offset = 0x01DAD668
instruction = "MOV             W0, #0x11F"

[[patches]]
# SceneCharacterSelect.<Start>d__84::MoveNext
offset = 0x01DB7338
instruction = "MOV             W0, #0x11F"

[[patches]]
# InformationPopup::StopMusic
offset = 0x0185D994
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x019EDC2C
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x019EDD10
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneOption.<Start>d__46::MoveNext
offset = 0x019F247C
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneGallery.<Start>d__52::MoveNext
offset = 0x01DBAF50
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneHelp.<Start>d__22::MoveNext
offset = 0x01DBC0E4
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FD090C
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneOption::Update
offset = 0x023EDB18
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneOption::SetPopup
offset = 0x023EE818
instruction = "MOV             W0, #0x11E"

[[patches]]
# SceneOption::FinishCorrection
offset = 0x023F1544
instruction = "MOV             W0, #0x11E"

[[patches]]
# TitleMenu::SetSound
offset = 0x017D9770
instruction = "CMP             W20, #0x11D"

[[patches]]
# GameManager::Initialize
offset = 0x01802C28
instruction = "MOV             W9, #0x11D"

[[patches]]
# GameManager::Initialize
offset = 0x01802F00
instruction = "MOV             W1, #0x11D"

[[patches]]
# GameSoundManager.<LoadSingleMusicAsync>d__8::MoveNext
offset = 0x01C256F8
instruction = "CMP             W9, #0x11C"
