[[patches]]
# GameSoundManager.<LoadSingleMusicAsync>d__8::MoveNext
offset = 0x01CB0D18
instruction = "CMP             W9, #0x108"

[[patches]]
# TitleMenu::SetSound
offset = 0x017D8260
instruction = "CMP             W20, #0x109"

[[patches]]
# GameManager::Initialize
offset = 0x01817F48
instruction = "MOV             W9, #0x109"

[[patches]]
# GameManager::Initialize
offset = 0x01818220
instruction = "MOV             W1, #0x109"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x0193300C
instruction = "MOV             W0, #0x10A"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x019330F0
instruction = "MOV             W0, #0x10A"

[[patches]]
# SceneGallery.<Start>d__53::MoveNext
offset = 0x01E14180
instruction = "MOV             W0, #0x10A"

[[patches]]
# SceneHelp.<Start>d__22::MoveNext
offset = 0x01E15314
instruction = "MOV             W0, #0x10A"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FADAD0
instruction = "MOV             W0, #0x10A"

[[patches]]
# TitleMenu::SetSound
offset = 0x017D8338
instruction = "MOV             W0, #0x111"

[[patches]]
# GallerySoundList::GetPlayingMusicID
offset = 0x01814604
instruction = "MOV             W0, #0x111"

[[patches]]
# GameManager::Initialize
offset = 0x01818218
instruction = "CMP             W8, #0x111"

[[patches]]
# AppData::CreateMusicIDList
offset = 0x0186BF40
instruction = "MOV             W1, #0x111"

[[patches]]
# SceneCharacterSelect::SetGameSetting
offset = 0x01AE4738
instruction = "CMP             W10, #0x111"

[[patches]]
# SceneCharacterSelect::SetMusicTitle
offset = 0x01AE4A38
instruction = "CMP             W21, #0x111"

[[patches]]
# StageSelectPanel::SetDetail
offset = 0x01AF2E5C
instruction = "CMP             W22, #0x111"

[[patches]]
# StageSoundList::Init
offset = 0x01AF3568
instruction = "CMP             W28, #0x111"

[[patches]]
# StageSoundList::SetStageSoundList
offset = 0x01AF37E4
instruction = "CMP             W8, #0x111"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01AF3EEC
instruction = "CMP             W19, #0x111"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01AF4214
instruction = "CMP             W9, #0x111"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01AF4334
instruction = "CMP             W9, #0x111"

[[patches]]
# StageSoundList::UpdateSort
offset = 0x01AF5340
instruction = "MOV             W1, #0x111"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01AF5B38
instruction = "CMP             W23, #0x111"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01AF5BA8
instruction = "CMP             W23, #0x111"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01AF60A4
instruction = "CMP             W22, #0x111"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01AF6114
instruction = "CMP             W22, #0x111"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE3A48
instruction = "CMP             W26, #0x111"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE3AEC
instruction = "CMP             W24, #0x111"

[[patches]]
# MusicData::.cctor
offset = 0x01BE4408
instruction = "MOV             W19, #0x111"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01BF5140
instruction = "MOV             W8, #0x111"

[[patches]]
# RuleSetting::Init
offset = 0x01F239FC
instruction = "MOV             W8, #0x111"

[[patches]]
# SceneGallery::get_IsPlaying
offset = 0x01FAC054
instruction = "CMP             W8, #0x111"

[[patches]]
# SceneGallery::Update
offset = 0x01FAC93C
instruction = "CMP             W8, #0x111"

[[patches]]
# SceneGallery::CheckBGM
offset = 0x01FACFF4
instruction = "CMP             W8, #0x111"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FAD30C
instruction = "CMP             W8, #0x111"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FAD324
instruction = "CMP             W8, #0x111"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FADAAC
instruction = "MOV             W8, #0x111"

[[patches]]
# SceneGallery::.ctor
offset = 0x01FAEEB4
instruction = "MOV             W8, #0x111"

[[patches]]
# SceneMainMenu::InitGameSetting
offset = 0x01FBA3A0
instruction = "MOV             W0, #0x111"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01AF419C
instruction = "CMP             W22, #0x110"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01AF42B4
instruction = "CMP             W22, #0x110"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01AF43C4
instruction = "CMP             W20, #0x110"

[[patches]]
# StageSelectPanel::PushButtonUD
offset = 0x01AF577C
instruction = "MOV             W1, #0x110"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01AF5F50
instruction = "MOV             W1, #0x110"

[[patches]]
# StageSelectPanel::PushButtonX
offset = 0x01AF66AC
instruction = "MOV             W1, #0x110"

[[patches]]
# MusicInfo::GetInfo
offset = 0x01BE3370
instruction = "CMP             W20, #0x110"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE37F4
instruction = "MOV             W1, #0x110"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE3848
instruction = "CMP             W20, #0x110"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE3888
instruction = "CMP             W21, #0x110"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BE3934
instruction = "CMP             W20, #0x110"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01BF4668
instruction = "MOV             W1, #0x110"

[[patches]]
# GameSoundManager.<LoadAllMusicAsync>d__9::MoveNext
offset = 0x01CAF900
instruction = "CMP             W20, #0x110"

[[patches]]
# AppData::SortMusic
offset = 0x01873E18
instruction = "CMP             W8, #0x10F"

[[patches]]
# AppData::SortMusic
offset = 0x01873E8C
instruction = "CMP             W8, #0x10F"

[[patches]]
# SceneCharacterSelect::Update
offset = 0x01ADA750
instruction = "MOV             W22, #0x10B"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01AF3F08
instruction = "MOV             W0, #0x10B"

[[patches]]
# SceneCharacterSelect.<CloseStageSelectPanel>d__115::MoveNext
offset = 0x01E054A0
instruction = "MOV             W0, #0x10B"

[[patches]]
# SceneCharacterSelect.<HandleErrorAsync>d__147::MoveNext
offset = 0x01E06898
instruction = "MOV             W0, #0x10B"

[[patches]]
# SceneCharacterSelect.<Start>d__84::MoveNext
offset = 0x01E10568
instruction = "MOV             W0, #0x10B"