[[patches]]
# TitleMenu::SetSound
offset = 0x017D9838
instruction = "MOV             W0, #0x134"

[[patches]]
# GallerySoundList::GetPlayingMusicID
offset = 0x017FF294
instruction = "MOV             W0, #0x134"

[[patches]]
# GameManager::Initialize
offset = 0x01802F00
instruction = "CMP             W8, #0x134"

[[patches]]
# AppData::CreateMusicIDList
offset = 0x01894550
instruction = "MOV             W1, #0x134"

[[patches]]
# AppData::InitReleaseItems
offset = 0x0189628C
instruction = "MOV             W9, #0x134"

[[patches]]
# AppData::.cctor
offset = 0x0189CF14
instruction = "MOV             W10, #0x134"

[[patches]]
# SceneCharacterSelect::SetGameSetting
offset = 0x01AEC2BC
instruction = "CMP             W10, #0x134"

[[patches]]
# SceneCharacterSelect::SetMusicTitle
offset = 0x01AEC5B8
instruction = "CMP             W21, #0x134"

[[patches]]
# StageSelectPanel::SetDetail
offset = 0x01B622EC
instruction = "CMP             W22, #0x134"

[[patches]]
# StageSoundList::Init
offset = 0x01B629F8
instruction = "CMP             W28, #0x134"

[[patches]]
# StageSoundList::SetStageSoundList
offset = 0x01B62C74
instruction = "CMP             W8, #0x134"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01B6337C
instruction = "CMP             W19, #0x134"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B636A4
instruction = "CMP             W9, #0x134"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B637C4
instruction = "CMP             W9, #0x134"

[[patches]]
# StageSoundList::UpdateSort
offset = 0x01B647D0
instruction = "MOV             W1, #0x134"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B64FC8
instruction = "CMP             W23, #0x134"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B65038
instruction = "CMP             W23, #0x134"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B65534
instruction = "CMP             W22, #0x134"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B655A4
instruction = "CMP             W22, #0x134"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA668
instruction = "CMP             W26, #0x134"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA70C
instruction = "CMP             W24, #0x134"

[[patches]]
# MusicData::.cctor
offset = 0x01BCB028
instruction = "MOV             W19, #0x134"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01C15578
instruction = "MOV             W20, #0x134"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01C15764
instruction = "MOV             W20, #0x134"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01C16388
instruction = "MOV             W20, #0x134"

[[patches]]
# ChallengeData.<InitializeAsync>d__4::MoveNext
offset = 0x01C5444C
instruction = "MOV             W8, #0x134"

[[patches]]
# RuleSetting::Init
offset = 0x01F09B9C
instruction = "MOV             W8, #0x134"

[[patches]]
# SceneGallery::get_IsPlaying
offset = 0x01FCEEF4
instruction = "CMP             W8, #0x134"

[[patches]]
# SceneGallery::Update
offset = 0x01FCF7DC
instruction = "CMP             W8, #0x134"

[[patches]]
# SceneGallery::CheckBGM
offset = 0x01FCFE94
instruction = "CMP             W8, #0x134"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FD01AC
instruction = "CMP             W8, #0x134"

[[patches]]
# SceneGallery::SetSoundTest
offset = 0x01FD01C4
instruction = "CMP             W8, #0x134"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FD09C8
instruction = "MOV             W8, #0x134"

[[patches]]
# SceneGallery::.ctor
offset = 0x01FD1DE0
instruction = "MOV             W8, #0x134"

[[patches]]
# SceneMainMenu::InitGameSetting
offset = 0x01FDD2A0
instruction = "MOV             W0, #0x134"

[[patches]]
# InformationData.<InitializeAsync>d__4::MoveNext
offset = 0x020E2448
instruction = "MOV             W21, #0x134"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B6362C
instruction = "CMP             W22, #0x133"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B63744
instruction = "CMP             W22, #0x133"

[[patches]]
# StageSelectPanel::SetBackGround
offset = 0x01B63854
instruction = "CMP             W20, #0x133"

[[patches]]
# StageSelectPanel::PushButtonUD
offset = 0x01B64C0C
instruction = "MOV             W1, #0x133"

[[patches]]
# StageSelectPanel::PushButtonHorizontal
offset = 0x01B653E0
instruction = "MOV             W1, #0x133"

[[patches]]
# StageSelectPanel::PushButtonX
offset = 0x01B65B3C
instruction = "MOV             W1, #0x133"

[[patches]]
# MusicData::GetInfo
offset = 0x01BC9F90
instruction = "CMP             W20, #0x133"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA414
instruction = "MOV             W1, #0x133"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA468
instruction = "CMP             W20, #0x133"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA4A8
instruction = "CMP             W21, #0x133"

[[patches]]
# MusicData::GetMusicIDList
offset = 0x01BCA554
instruction = "CMP             W20, #0x133"

[[patches]]
# MusicData::InitializeAsync::MoveNext
offset = 0x01C153F4
instruction = "MOV             W1, #0x133"

[[patches]]
# GameSoundManager::LoadAllMusicAsync::MoveNext
offset = 0x01C24390
instruction = "CMP             W20, #0x133"

[[patches]]
# AppData::SortMusic
offset = 0x0189C428
instruction = "CMP             W8, #0x132"

[[patches]]
# AppData::SortMusic
offset = 0x0189C49C
instruction = "CMP             W8, #0x132"

[[patches]]
# SceneCharacterSelect::Update
offset = 0x01AE22E0
instruction = "MOV             W22, #0x12E"

[[patches]]
# StageSelectPanel::PlaySampleBGM
offset = 0x01B63398
instruction = "MOV             W0, #0x12E"

[[patches]]
# SceneChallenge.<Start>d__25::MoveNext
offset = 0x01DAB89C
instruction = "MOV             W0, #0x12E"

[[patches]]
# SceneCharacterSelect.<CloseStageSelectPanel>d__115::MoveNext
offset = 0x01DAC320
instruction = "MOV             W0, #0x12E"

[[patches]]
# SceneCharacterSelect.<HandleErrorAsync>d__147::MoveNext
offset = 0x01DAD
instruction = "MOV             W0, #0x12E"

[[patches]]
# SceneCharacterSelect.<Start>d__84::MoveNext
offset = 0x01DB73E8
instruction = "MOV             W0, #0x12E"

[[patches]]
# InformationPopup::StopMusic
offset = 0x0185D994
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x019EDC8C
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneMainMenu.<Start>d__85::MoveNext
offset = 0x019EDD70
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneOption.<Start>d__46::MoveNext
offset = 0x019F24DC
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneGallery.<Start>d__52::MoveNext
offset = 0x01DBB030
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneHelp.<Start>d__22::MoveNext
offset = 0x01DBC1C4
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneGallery::SetNowPlaying
offset = 0x01FD09EC
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneOption::Update
offset = 0x023EDBF8
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneOption::SetPopup
offset = 0x023EE8F8
instruction = "MOV             W0, #0x12D"

[[patches]]
# SceneOption::FinishCorrection
offset = 0x023F1624
instruction = "MOV             W0, #0x12D"

[[patches]]
# TitleMenu::SetSound
offset = 0x017D9760
instruction = "CMP             W20, #0x12C"

[[patches]]
# GameManager::Initialize
offset = 0x01802C2C
instruction = "MOV             W9, #0x12C"

[[patches]]
# GameManager::Initialize
offset = 0x01802F08
instruction = "MOV             W1, #0x12C"

[[patches]]
# GameSoundManager::LoadSingleMusicAsync::MoveNext
offset = 0x01C257A8
instruction = "CMP             W9, #0x12B"

[[patches]]
# DLCManager::GetIsDLCAvailable
offset = 0x01DE7780
instruction = "B               0xFC"
override_patch = true

[[patches]]
# DLCManager::GetIsDLCAvailable
offset = 0x01DE7880
instruction = "MOV             W0, #1"
override_patch = true

[[patches]]
# SpecialRuleInfo::ctor
offset = 0x01D26D98
instruction = "MOV             W8, #1"
override_patch = true
